name: Build font and specimen

on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-fonts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build font
      run: make build
    - uses: actions/upload-artifact@v3
      with:
        name: built-fonts
        path: 'fonts'
  