name: Test fonts

on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:
  get-fonts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Get font
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build.yaml
        name: built-fonts 
        paths: built-fonts

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - uses: m4rc1e/font-browser-tests-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path: "./built-fonts/variable/*.ttf"
        fetch-before: "googlefonts"
        path-before: "*.ttf"
        run-diffenator: false # we only want browser screenshot diffs
        run-diffbrowsers: true

#  diff:
#    needs:
#      - get-fonts
#    runs-on: ubuntu-latest
#    steps:
#      - uses: m4rc1e/font-browser-tests-action@main
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path: "./built-fonts/variable/*.ttf"
#          fetch-before: "googlefonts"
#          path-before: "*.ttf"
#          run-diffenator: true
#          run-diffbrowsers: false
#